### ISSUE TITLE
No launch file in rtabmap_ros ?

### ISSUE THREAD

**Issue by MrDarknessWolf** [simonbogh/realsense-d435-rtab-map-in-ROS2#1]
im confused, i know there must be a file for launching the program but its no longer there for foxy

**Comment by simonbogh** [comment]
Do you have both of these packages installed?

```
sudo apt install ros-foxy-realsense2-camera
sudo apt install ros-foxy-rtabmap-ros
```

**Comment by MrDarknessWolf** [comment]
> Do you both of these packages installed?
> 
> ```
> sudo apt install ros-foxy-realsense2-camera
> sudo apt install ros-foxy-rtabmap-ros
> ```

yep i have both installed yet it cant find the launch file in the opt/ros/foxy/shared/rtabmap_ros and when you check inside with ls it doesnt really have anything there that launches 
![image](https://github.com/simonbogh/realsense-d435-rtab-map-in-ROS2/assets/49293724/35b8f826-de05-4445-bf9c-935555acdb79)

**Comment by MrDarknessWolf** [comment]
Also to clarify I'm using Ubuntu 20.4 with Ros Foxy , a D435i in a Jetson nano, which for some reason Rtabmap in Ros 1 works flawlessly but in Ros 2 , using Rtabmap_launch rtabmap.launch.py it crashes but when using the launch file for the examples it opens up the visuzalizer but doesn't connect to the topics and idk why

**Comment by simonbogh** [comment]
You'll find the launch file in `/opt/ros/foxy/share/rtabmap_launch/launch`.

Just note, this example is for `D435` and not `D435i`. You may require some other topics and setup. Use the ROS1 examples as a reference: http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping.

I may add an example for `D435i` when I get the camera back.

**Comment by simonbogh** [comment]
ROS1 examples for mapping mode:

**D415/D435**
```
 $ roslaunch rtabmap_launch rtabmap.launch \
    rtabmap_args:="--delete_db_on_start" \
    depth_topic:=/camera/aligned_depth_to_color/image_raw \
    rgb_topic:=/camera/color/image_raw \
    camera_info_topic:=/camera/color/camera_info \
    approx_sync:=false
```

**D435i/L515**
```
 $ roslaunch rtabmap_launch rtabmap.launch \
    rtabmap_args:="--delete_db_on_start --Optimizer/GravitySigma 0.3" \
    depth_topic:=/camera/aligned_depth_to_color/image_raw \
    rgb_topic:=/camera/color/image_raw \
    camera_info_topic:=/camera/color/camera_info \
    approx_sync:=false \
    wait_imu_to_init:=true \
    imu_topic:=/rtabmap/imu
```

**Comment by MrDarknessWolf** [comment]
> ROS1 examples for mapping mode:
> 
> **D415/D435**
> 
> ```
>  $ roslaunch rtabmap_launch rtabmap.launch \
>     rtabmap_args:="--delete_db_on_start" \
>     depth_topic:=/camera/aligned_depth_to_color/image_raw \
>     rgb_topic:=/camera/color/image_raw \
>     camera_info_topic:=/camera/color/camera_info \
>     approx_sync:=false
> ```
> 
> **D435i/L515**
> 
> ```
>  $ roslaunch rtabmap_launch rtabmap.launch \
>     rtabmap_args:="--delete_db_on_start --Optimizer/GravitySigma 0.3" \
>     depth_topic:=/camera/aligned_depth_to_color/image_raw \
>     rgb_topic:=/camera/color/image_raw \
>     camera_info_topic:=/camera/color/camera_info \
>     approx_sync:=false \
>     wait_imu_to_init:=true \
>     imu_topic:=/rtabmap/imu
> ```

Yeah thats the one that works for Ros1, in Ros2 Foxy from the tutorial it seems the launc.py file is missing from the repository even if you build it fromsource it doesnt appear on the instalation files

**Comment by simonbogh** [comment]
Did you check `/opt/ros/foxy/share/rtabmap_launch/launch `? Check my post above.

**Comment by MrDarknessWolf** [comment]
> Did you check `/opt/ros/foxy/share/rtabmap_launch/launch `? Check my post above.

Yeah is there , surprisingly, it crashes when trying to open the launch file

**Comment by simonbogh** [comment]
I will close the issue. I will add an example for D435i when I get the camera. Feel free to share if you get it to work.
